import time
import threading


is_command_busy = False
last_completion_time = 0
#create function to manage timing of commands and keep them in thread for faster processing and prevent crashes.
def command(command_func, name, *args, **kwargs):
    global is_command_busy, last_completion_time

    #if the drone is already carrying out a command, ignore new gesture triggers
    if is_command_busy or (time.time() - last_completion_time < 1):
        return

    def work():
        global is_command_busy, last_completion_time
        is_command_busy = True
        print(f"Command: {name}")

        try:
            command_func(*args, **kwargs)
            #time.sleep(0.05) #small delay before next command
        except Exception as e:
            print(f"Command error ({name}): {e}")
        finally:
            is_command_busy = False
            last_completion_time = time.time()

    threading.Thread(target=work, daemon=True).start()
    return True

def is_busy():
    """
    True while a blocking SDK command (takeoff / land / move_down) is still
    running in its background thread.

    This has to be a function, not a plain read of is_command_busy.
    drone_control.py does 'from funcs import *', which copies the VALUE of
    is_command_busy once at import time - so reading that copy would always
    report whatever it was at start-up (False) no matter what command()
    does later. Calling a function reads the live global instead.
    """
    return is_command_busy


def swipe_control(curr_rel_pos, anchor_rel_pos, threshold=0.04, rc_speed=30):
    """
    Works out a movement direction from how far the fingertip has drifted
    away from where it sat when the gesture started.

    curr_rel_pos / anchor_rel_pos are the fingertip position RELATIVE TO THE
    WRIST - not its raw position in the camera frame. That distinction is
    the whole reason this doesn't fight the yaw-centring: when the drone
    rotates to re-centre the person, their entire hand slides across the frame, but their
    fingertip does not move relative to their wrist, so no phantom swipe is
    generated by the drone's own rotation.

    This function does maths ONLY - it never commands the drone. All four RC
    channels must go out in one 'rc' command, so sending happens in a single
    place in drone_control.py.

    Returns: (left_right, forward_backward, up_down)
    """
    # No anchor yet (very first frame of the gesture) - hold still this frame.
    if anchor_rel_pos is None or curr_rel_pos is None:
        return 0, 0, 0

    #calculate difference in distance between the current position and the anchor position of the finger
    dx = curr_rel_pos[0] - anchor_rel_pos[0]
    dy = curr_rel_pos[1] - anchor_rel_pos[1]

    left_right = 0
    forward_backward = 0
    up_down = 0

    # Whichever axis moved furthest wins, so a sloppy diagonal still resolves
    # to one clean direction rather than two half-strength commands.
    if abs(dx) > threshold and abs(dx) > abs(dy):
        if dx > 0:
            left_right = -rc_speed    # finger moved right -> roll left
        else:
            left_right = rc_speed     # finger moved left  -> roll right

    # elif abs(dy) > threshold and abs(dy) > abs(dx):
    #     # MediaPipe's y axis grows DOWNWARDS, so a negative dy means the
    #     # fingertip actually moved up on screen.
    #     if dy < 0:
    #         up_down = rc_speed        # finger moved up   -> climb
    #     else:
    #         up_down = -rc_speed       # finger moved down -> descend

    return left_right, forward_backward, up_down


def yaw_centering(hand_center_x, deadzone=0.12, max_yaw_speed=40):
    """
    Works out how fast to spin the drone so the person stays centred in shot.

    hand_center_x is the WRIST's x position, 0.0 (hard left of frame) to 1.0
    (hard right). The wrist is used rather than the fingertip because the
    wrist stays put while the finger is being flicked around - so the drone
    tracks the person, not the finger.

    Returns: yaw velocity (positive = rotate clockwise/right).
    """
    # No hand visible this frame - don't rotate.
    if hand_center_x is None:
        return 0

    #Calculate How far off-centre is the person? 0.5 is dead centre of the frame.
    error = hand_center_x - 0.5

    # Deadzone: if they're roughly centred, don't yaw at all. Without this
    # the drone shifts back and forth around centre and never settles.
    if abs(error) < deadzone:
        return 0

    # Proportional control: further off-centre = faster correction. Similar to PID. for Smoother control.
    # error maxes out at 0.5, so error/0.5 scales it into -1.0 .. 1.0.
    yaw = int(max_yaw_speed * (error / 0.5))

    #Clamp speed to max allowed.
    if yaw > max_yaw_speed:
        yaw = max_yaw_speed
    elif yaw < -max_yaw_speed:
        yaw = -max_yaw_speed

    return yaw



def timestamp():
    """Filename-safe timestamp. Hyphens not colons - Windows forbids ':' in
    filenames."""
    return time.strftime("%d-%m-%Y_%H-%M-%S") #day month year _ hour minute second

def orbit_control():
    pass
def dronie_control():
    pass